name: test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    - develop

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: ['12', '14', '16']
    steps:
      - uses: actions/checkout@v2
      - name: Run tests on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm run test
